server.port=8080
spring.application.name=soporte-tecnico-api

# Swagger / OpenAPI UI disponible en: http://localhost:8080/swagger-ui.html
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
